#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : perl-Params-ValidationCompiler
Version  : 0.26
Release  : 8
URL      : http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/Params-ValidationCompiler-0.26.tar.gz
Source0  : http://search.cpan.org/CPAN/authors/id/D/DR/DROLSKY/Params-ValidationCompiler-0.26.tar.gz
Summary  : 'Build an optimized subroutine parameter validator once, use it forever'
Group    : Development/Tools
License  : Artistic-2.0
Requires: perl-Params-ValidationCompiler-doc
BuildRequires : perl(Eval::Closure)
BuildRequires : perl(Exception::Class)
BuildRequires : perl(Importer)
BuildRequires : perl(Specio)
BuildRequires : perl(Sub::Info)
BuildRequires : perl(Test2::V0)

%description
# NAME
Params::ValidationCompiler - Build an optimized subroutine parameter validator once, use it forever

%package doc
Summary: doc components for the perl-Params-ValidationCompiler package.
Group: Documentation

%description doc
doc components for the perl-Params-ValidationCompiler package.


%prep
%setup -q -n Params-ValidationCompiler-0.26

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
if test -f Makefile.PL; then
%{__perl} Makefile.PL
make  %{?_smp_mflags}
else
%{__perl} Build.PL
./Build
fi

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make TEST_VERBOSE=1 test || :

%install
rm -rf %{buildroot}
if test -f Makefile.PL; then
make pure_install PERL_INSTALL_ROOT=%{buildroot}
else
./Build install --installdirs=site --destdir=%{buildroot}
fi
find %{buildroot} -type f -name .packlist -exec rm -f {} ';'
find %{buildroot} -depth -type d -exec rmdir {} 2>/dev/null ';'
find %{buildroot} -type f -name '*.bs' -empty -exec rm -f {} ';'
%{_fixperms} %{buildroot}/*

%files
%defattr(-,root,root,-)
/usr/lib/perl5/site_perl/5.26.1/Params/ValidationCompiler.pm
/usr/lib/perl5/site_perl/5.26.1/Params/ValidationCompiler/Compiler.pm
/usr/lib/perl5/site_perl/5.26.1/Params/ValidationCompiler/Exceptions.pm

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*
